final FULL_BUILD = params.FULL_BUILD

final PROJECT_TYPE = 'java'

final PROJECT_NAME = "GSXR/micro1"

pipeline {
  agent any

  stages {
    stage("Provision") {
      steps {
        provision(PROJECT_TYPE)
      }
    }
  	
    stage('Build') {
      steps {
      	dir("Marrakech") {
      	  bat 'mvn package'
      	}
      }
    }
    
    stage('Make Container') {
      steps {
      	bat "docker build -t ${PROJECT_NAME}:${env.BUILD_ID} ./Marrakech/"
        bat "docker tag ${PROJECT_NAME}:${env.BUILD_ID} ${PROJECT_NAME}:latest"
      }
    }
  }
}
