genPipe {
  branch = 'master'
  scmUrl = 'https://github.com/Elixear/Marrakesh.git'

  name = "gsxr/micro1"
  infrastructure = 'docker'
  lang = "java"
  
  unitTest = true
  integrationTest = true
  
  qualityAnalysis = true
  
  nexusRepository = "localhost:8081"
}
